GET http://localhost:5000/


### Get all student
GET http://localhost:5000/api/student


### Add student
POST http://localhost:5000/api/student/register
Content-Type: application/json

{
    "fullName": "Anuj Sharma",
    "Rollno": "18etccs002",
    "email": "18etccs002@technonjr.org",
    "password": "password"
}


### Login student
POST http://localhost:5000/api/student/login
Content-Type: application/json

{
    "email": "18etccs002@technonjr.org",
    "password": "password"
}

### Get all teachers
GET http://localhost:5000/api/teacher/subject


### Add teacher
POST http://localhost:5000/api/teacher/register
Content-Type: application/json

{
    "fullName": "GK",
    "subject": "JAVA",
    "email": "gk@technonjr.org",
    "password": "password"
}


### Login teacher
POST http://localhost:5000/api/teacher/login
Content-Type: application/json

{
    "email": "gk@technonjr.org",
    "password": "password"
}


### Add admin
POST http://localhost:5000/api/admin/register
Content-Type: application/json

{
    "fullName": "director",
    "email": "director@technonjr.org",
    "password": "password"
}


### Login teacher
POST http://localhost:5000/api/admin/login
Content-Type: application/json

{
    "email": "director@technonjr.org",
    "password": "password"
}

### Get attendance of student by roll no
POST  http://localhost:5000/api/attendance/eachStudent
Content-Type: application/json

{
    "Rollno":"18etccs001",
    "subject":"JAVA"
}
### Get Attendance

GET http://localhost:5000/api/attendance
Content-Type: application/json